## Cria Usuário
POST http://localhost:3000/usuario
Content-Type: application/json

{
  "matricula": "133822", 
  "nome":"Gustavo",
  "senha": "senha123",
  "tipoUsuario":"Aluno" 
}

### Lista Todas Usuários

GET http://localhost:3000/usuario


### Lista um Usuário pela matrícula

GET http://localhost:3000/usuario/133822

### Atualiza Usuário

PATCH  http://localhost:3000/usuario/133822
Content-Type: application/json

{
  "matricula": "133822", 
  "nome":"Gustavo att",
  "senha": "senha123 att",
  "tipoUsuario":"Professor" 
}
### Remove Usuário

DELETE   http://localhost:3000/usuario/133822
