## Cria Aluno
POST http://localhost:3000/aluno
Content-Type: application/json

{
  "nome": "Gustavo",
  "matricula": "133822", 
  "codCurso": "7702"
}

### Lista Todos Alunos

GET http://localhost:3000/aluno


### Lista um Aluno pela matrícula

GET http://localhost:3000/aluno/133822

### Atualiza Aluno

PATCH  http://localhost:3000/aluno/133822

{
  "nome": "Gustavo att",
  "matricula": "133822 att", 
  "codCurso": "7702 att"
}

### Remove Aluno

DELETE   http://localhost:3000/aluno/133822
